"use client";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/Header"
import Footer from "../components/Footer"
import "./globals.css";
import * as React from "react";

// 1. import `HeroUIProvider` component
import { HeroUIProvider } from "@heroui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <HeroUIProvider>
          {children}
        </HeroUIProvider>
        <Footer />
      </body>
    </html>
  );
}
